Repository pdybowski/village-defense, pull requests merged in 2021-02, with the labels that each got.

#84 Game over dialog
  README.md
  package-lock.json
  package.json
  src/app/audio.ts
  src/app/components/gameOverModal.ts
  src/app/components/gameSettingsModal.ts
  src/app/components/index.ts
  src/app/components/info.ts
  src/app/components/infoModal.ts
  src/app/components/popup.ts
  src/app/constants/game.ts
  src/app/game.ts
  src/app/models/buildings/wall.ts
  src/app/screens/gamepage/index.ts
  src/app/screens/homepage/index.ts
  src/assets/css/components/gameOverModal.css
  src/assets/css/components/infoView.css
  src/assets/css/components/popup.css
  src/core/bootstrap.ts
  webpack.common.js
Labels: feature

#92 Add game messages
  src/app/game.ts
  src/app/models/buildings/building.ts
  src/app/models/buildings/goldmine.ts
  src/app/screens/gamepage/index.ts
  src/assets/css/global.css
  src/assets/css/screens/gameScreen.css
  src/index.html
Labels: feature

#102 Unit and e2e tests
  .gitignore
  __tests__/capitalizeFirstLetter.test.ts
  __tests__/createElement.test.ts
  __tests__/date.test.ts
  __tests__/game.test.ts
  __tests__/getFractionForName.test.ts
  __tests__/helpers.test.ts
  __tests__/random.test.ts
  cypress.json
  cypress/integration/game_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  jest.config.js
  package-lock.json
  package.json
  src/app/components/battle.ts
  src/app/game.ts
  src/app/models/buildings/building.ts
  src/app/screens/gamepage/index.ts
  src/app/utils/audio.ts
  src/app/utils/date.ts
  src/app/utils/index.ts
Labels: test

#114 rename a method to reduce build time
  src/app/game.ts
  src/app/models/buildings/townhall.ts
Labels: bug
